### ISSUE TITLE
Design WEE Logo

### ISSUE THREAD

**Issue by CaitMS** [COS301-SE-2024/Web-Exploration-Engine#129]

**Comment by MignonErasmus** [comment]
Transparent logo:
![Image](https://github.com/user-attachments/assets/4a438623-d009-4c0c-bf24-e1bdec67ef88)


Logo:
![Image](https://github.com/user-attachments/assets/ab33a704-e404-40e0-85d3-56fd61c614cc)

I'll create more variations of the logo in due course and add it to our google drive😊
