### ISSUE TITLE
Sentiment analysis UI design

### ISSUE THREAD

**Issue by CaitMS** [COS301-SE-2024/Web-Exploration-Engine#251]

**Comment by MignonErasmus** [comment]
![image](https://github.com/user-attachments/assets/0e2cb17e-6f10-4710-9e52-0307d4294c3b)

![image](https://github.com/user-attachments/assets/2f07ee78-79d3-4db0-9b97-62b599b5d833)

![image](https://github.com/user-attachments/assets/646c3cfb-c6b6-4ba0-a9a9-f9a646a2e7ef)
