### ISSUE TITLE
Clarification of emotional confidence scores

### ISSUE THREAD

**Issue by CaitMS** [COS301-SE-2024/Web-Exploration-Engine#513]
What did "emotions confidence score" mean => does Anger 1% mean that you are 1% confident that the site is "angry"?? Not sure this description makes sense

-- maybe on display the top 3 most confident, not sure I really understand the algorithm either

**Comment by Johane-B** [comment]
A score of 1% for Anger means there is a 1% likelihood that the content conveys the emotion of anger. This does not suggest that the site is "angry"; it simply indicates that the model has low confidence in that emotion being present.


Maybe add this part " Each score indicates the model's confidence in detecting a specific emotion based on the metadata." 

So the information would look like this:
Emotions Confidence Score
By analyzing users' domain-specific metadata, we can discern specific emotional cues. This capability empowers users to fine-tune their metadata settings, thereby invoking the desired emotional responses. **Each score indicates the model's confidence in detecting a specific emotion based on the metadata**

Note: WEE cannot guarantee the accuracy of the analysis as it is based on machine learning models.
