### ISSUE TITLE
Scraping result page UI

### ISSUE THREAD

**Issue by CaitMS** [COS301-SE-2024/Web-Exploration-Engine#86]

**Comment by MignonErasmus** [comment]
![image](https://github.com/COS301-SE-2024/Web-Exploration-Engine/assets/126988676/37835f3a-2458-4d48-ae12-3e339e1fe4ab)

**Comment by MignonErasmus** [comment]
![Image](https://github.com/COS301-SE-2024/Web-Exploration-Engine/assets/126988676/3c83ff2f-6b2f-4104-9154-c1dfc46c8f3d)

Instead of tiles/cards, change the scrape results to be displayed in a table (still with pagination etc.)
