### ISSUE TITLE
Intergration testing

### ISSUE THREAD

**Issue by CaitMS** [COS301-SE-2024/Web-Exploration-Engine#89]
Frontend Integration Tests Needed for the following :

- [ ] routing
- [ ] login
- [ ] signup

Webscraper Integration Tests Needed for the following :

- [x] routing

**Comment by siyamthandandlovu** [comment]
Implement integration tests as component vs e2e tests
https://docs.cypress.io/guides/tooling/code-coverage#Code-coverage-as-a-guide
